---
title: "Client Report - Can You Predict That?"
subtitle: "Unit 4 Task 1"
author: "Rebecca Hockman"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *
from sklearn.model_selection import train_test_split
from sklearn import metrics
import requests 
import io  
# add the additional libraries you need to import for ML here

LetsPlot.setup_html(isolated_frame=True)

```


```{python}
# import your data here using polars and the URL

url = "https://raw.githubusercontent.com/byuidatascience/data4dwellings/master/data-raw/dwellings_ml/dwellings_ml.csv"

response = requests.get(url)

df = pl.read_csv(io.BytesIO(response.content))


```

## QUESTION

1. __Take time to get to know your data.__ Based on some initial exploration, identify 3 variables in the dataset you think will have strong predictive ability for determining if a house was built before 1980. Explain/justify the reasoning behind your guesses (for example with plots).

Based on the data, Some variables that I would think have a strong predictive ability are the condition columns for one. This is because I would think that the newer homes are in a better condition that those that are older.

I also think that the size of the garage would be bigger for more current homes, as people like to have more storage space, and more cars in their homes.

The last variable I would like is the number of floors. I think that older houses are more likely to have one floor and maybe a basement, while newer houses are more likely to build up.

```{python}
# Optional: code you used to get to know your data
```

1. __Build a classification model labeling houses as being built “before 1980” or “during or after 1980”.__ Your goal is to reach or exceed 90% accuracy. Report your final model choice and any other model parameters you may have tweaked (train-test split ratio, tuning parameters, etc).  

The first thing that I did here was remove the columns that are already predicted, and the identifier column. This removes the columns that will effect the outcome. I then set the test data to 20%, with 80% being used for training. I used the random forest classifier with 200 estimators. This got me to 93% accuracy.

```{python}
# Include and execute your code here
# Don't forget, you need another import statement to import the desired ML model from sklearn

y = df.select("before1980")
X = df.drop(["before1980", "yrbuilt", "parcel"])
from sklearn.model_selection import train_test_split
X_np = X.to_numpy()
y_np = y.to_numpy().ravel()
X_train, X_test, y_train, y_test = train_test_split(
    X_np,
    y_np,
    test_size=0.2,
    random_state=42
)
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)
model.fit(X_train, y_train)
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

```

