---
title: "Client Report -How good is it, really?"
subtitle: "Unit 4 Task 2"
author: "Rebecca Hockman"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *
from sklearn.model_selection import train_test_split
from sklearn import metrics
import requests
import io
from sklearn.inspection import permutation_importance
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
# add the additional libraries you need to import for ML here

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# import your data here using polars and the URL

url = "https://raw.githubusercontent.com/byuidatascience/data4dwellings/master/data-raw/dwellings_ml/dwellings_ml.csv"

response = requests.get(url)

df = pl.read_csv(io.BytesIO(response.content))

# Machine from last assignment

y = df.select("before1980")
X = df.drop(["before1980", "yrbuilt", "parcel"])
from sklearn.model_selection import train_test_split
X_np = X.to_numpy()
y_np = y.to_numpy().ravel()
X_train, X_test, y_train, y_test = train_test_split(
    X_np,
    y_np,
    test_size=0.2,
    random_state=42
)
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)
model.fit(X_train, y_train)
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)


```

## QUESTION 1

1. __Describe the quality of your classification model using 2-3 different evaluation metrics.__ You also need to explain how to define/interpret each of the evaluation metrics you use.  

before 1980
Accuracy - the percentage of how often the predictions are correct
precision - the amount that are true/predicted to be true
recall - gives you the actual number from the data to compare

I think that with this dataset, it is more important to have precision in your data. This tells us how much of the data that was projected to be correct is actually correct. In this case, it tells us how many of the of the houses estimated to have been built before 1980 were actually built before 1980.

This tells us that there is a 94% chance that the positive data is correct.

```{python}
# Include and execute your code here
# Don't forget, you need another import statement to import the desired ML model from sklearn

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report


accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("\nClassification Report")
print(classification_report(y_test, y_pred))

```


## QUESTION 2

1. __Justify your classification model by discussing the most important features selected by your model.__ This discussion should include a plot of permutation importance values for the most important features. Were there any features you thought would be importance but weren't?

I thought that garage type would be the most important but I wasn't expecting the number of bathrooms to be so high on the list. As we look at houses though I am noticing that older houses tend to have less bathrooms. 

```{python}
# Include and execute your code here

from sklearn.inspection import permutation_importance
import polars as pl

results = permutation_importance(
    model,
    X_test,
    y_test,
    n_repeats=10,
    random_state=17
)

df_importance = pl.DataFrame({
    "feature": X.columns,
    "perm_imp": results.importances_mean
}).sort("perm_imp", descending=True)

df_importance.head(10)

```

## QUESTION 3

1. __For the 3 most important features, explain their relationship to the target variable. Use a plot to illustrate the relationship.__ (3 plots minimum)

The first plot shows that there is a huge change from 1980 for the type of garage. 
The second plot is the abstract period, which differs slightly between 1980 and not, but the difference tells you that homes with an abstrprd over 1119 is from after 1980
The last plot is on whether or not there is one story. It looks like homes before 1980 are more likely to only have one story

```{python}
# Include and execute your code here

results = permutation_importance(
    model,
    X_test,
    y_test,
    n_repeats=10,
    random_state=17
)

df_importance = pl.DataFrame({
    "feature": X.columns,
    "perm_imp": results.importances_mean
}).sort("perm_imp", descending=True)

top3 = df_importance.head(3)
top_features = top3["feature"].to_list()

top3
```


```{python}
feature1 = top_features[0]

df_plot1 = df.group_by("before1980").agg(
    pl.col(feature1).mean().alias("mean_value")
)

(
    ggplot(df_plot1, aes(x="before1980", y="mean_value")) +
    geom_bar(stat="identity") +
    labs(
        title=f"Average {feature1} by Home Age",
        x="Built Before 1980 (1 = Yes, 0 = No)",
        y=f"Average {feature1}"
    )
)
```


```{python}
feature2 = top_features[1]

df_plot2 = df.group_by("before1980").agg(
    pl.col(feature2).mean().alias("mean_value")
)

(
    ggplot(df_plot2, aes(x="before1980", y="mean_value")) +
    geom_bar(stat="identity") +
    labs(
        title=f"Average {feature2} by Home Age",
        x="Built Before 1980 (1 = Yes, 0 = No)",
        y=f"Average {feature2}"
    )
)
```


```{python}
feature3 = top_features[2]

df_plot3 = df.group_by("before1980").agg(
    pl.col(feature3).mean().alias("mean_value")
)

(
    ggplot(df_plot3, aes(x="before1980", y="mean_value")) +
    geom_bar(stat="identity") +
    labs(
        title=f"Average {feature3} by Home Age",
        x="Built Before 1980 (1 = Yes, 0 = No)",
        y=f"Average {feature3}"
    )
)
```