---
title: "Client Report - Flights: Column Aggregation"
subtitle: "Unit 2 Task 2"
author: "Rebecca Hockman"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```

## QUESTION 1

__Calculate the sample size (i.e. number of observations) for each airport in each year__. What do you notice?

Early Years of recording are inconsistant, getting items such as 10,11, or 9 observations per year, whereas the more recent years have a consistant 12 observations a year.

```{python}
# Include and execute your code here
sample_sizes = (
    df
    .group_by(["airport_code", "year"])
    .agg(
        pl.count().alias("n_observations")
    )
    .sort(["airport_code", "year"])
)

sample_sizes



```

## QUESTION 2

1. __Which airport has the worst delays?__ Describe the metric you chose, and why you chose it to determine the “worst” airport. Your answer should include a summary table that lists (for each airport) the total number of flights, total number of delayed flights, proportion of delayed flights, and average delay time in hours. 

I think that the percentage of flights that are delayed is the most important for finding the "worst" airport. In this case I divided the delayed flights with the number of flights total and multiplied by 100 to get a percentage of flights. This makes "SFO" the worst airport.

```{python}
# Include and execute your code here
summary = (
    df
    .group_by("airport_code")
    .agg(
        pl.sum("num_of_flights_total").alias("total_flights"),
        pl.sum("num_of_delays_total").alias("delayed_flights"),
        pl.sum("minutes_delayed_total").alias("total_delay_minutes")
    )
    .with_columns(
        (pl.col("delayed_flights") / pl.col("total_flights"))
            .alias("prop_delayed"),
        (pl.col("total_delay_minutes") / pl.col("delayed_flights") / 60)
            .alias("avg_delay_hours")
    )
    .select(
        "airport_code",
        "total_flights",
        "delayed_flights",
        "prop_delayed",
        "avg_delay_hours"
    )
    .sort(["prop_delayed", "avg_delay_hours"], descending=[True, True])
)

summary




```

## QUESTION 3

__Create a barplot showing the proportion of all flights that are delayed at each airport. Describe what you learn from this graph.__  

You can tell from this graph that "SFO" has a little over 10% more delays than "SLC"
```{python}
# Include and execute your code here
ggplot(summary, aes(x="airport_code", y="prop_delayed")) + \
    geom_bar(stat="identity") + \
    labs(
        title="Percentage of Delayed Flights by Airport",
        x="Airport",
        y="Proportion Delayed"
    ) + \
    theme_minimal()


```

## QUESTION 4

__When controlling for airport and month, what is the trend in delayed flights over the years?__ For each row, calculate a ratio: number of delayed flights over the average number of delayed flights at that airport in that month. Then create a polished boxplot of the results, with year along the x axis. What does a point above 1 represent and what does a point below 1 represent? What insights do you gain from this plot?  What trend do you see, if any? Is it a good trend or bad trend?

1 represents a center of the average. The more points above 1 represents the more flights that are delayed. As the years go on, you can see the boxes get smaller and closer to the line, meaning an improvement in consistancy.

```{python}
# Include and execute your code here
avg_delays = (
    df
    .group_by(["airport_code", "month"])
    .agg(
        pl.mean("num_of_delays_total").alias("avg_monthly_delays")
    )
)
df_ratio = df.join(
    avg_delays,
    on=["airport_code", "month"]
)
df_ratio = df_ratio.with_columns(
    (pl.col("num_of_delays_total") / pl.col("avg_monthly_delays"))
    .alias("delay_ratio")
)
df_ratio = df_ratio.filter(pl.col("year").is_not_null())

#boxplot
ggplot(
    df_ratio,
    aes(x="year", y="delay_ratio")
) + \
    geom_boxplot() + \
    geom_hline(yintercept=1, linetype="dashed") + \
    scale_x_continuous(format="d") + \
    labs(
        title="Relative Flight Delays by Year",
        x="Year",
        y="Delay Ratio"
    ) + \
    theme_minimal()




```